// presets.js
document.querySelectorAll("[data-run]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-run]").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.runType=b.dataset.run});
document.querySelectorAll("[data-study]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-study]").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.studyType=b.dataset.study;updateJobReady()});
const presets={continuity:{mode:"elliptic",seedLock:.58,shellScale:1.02,shellCoupling:.7,cacheThreshold:.22,rates:[.18,.06,-.04,.04,-.02,.01]},cinema:{mode:"elliptic",seedLock:.3,shellScale:1.12,shellCoupling:.92,cacheThreshold:.3,rates:[.32,.11,-.09,.08,-.06,.04]},parallax:{mode:"omega",seedLock:.2,shellScale:1.34,shellCoupling:1.45,cacheThreshold:.24,rates:[.5,.28,-.16,.22,-.12,.09]},dream:{mode:"omega",seedLock:.12,shellScale:1.55,shellCoupling:.55,cacheThreshold:.34,rates:[.72,-.38,.44,.31,-.27,.19]},sway:{mode:"sway",seedLock:.42,shellScale:1.08,shellCoupling:1.1,cacheThreshold:.27,rates:[.24,.09,-.05,.07,-.03,.02]}};
const promptTreatments={continuity:"Unbroken identity-first tracking: preserve exact anatomy, silhouette, material, lighting logic, and spatial orientation from frame to frame; measured physical motion with no morphing, substitution, costume drift, or discontinuous camera jumps.",cinema:"A composed cinematic orbit with deliberate lens language, graceful elliptical camera movement, controlled depth separation, motivated light, restrained spectacle, and stable subject identity throughout the sequence.",parallax:"Pronounced deep parallax: foreground, subject, architecture, and horizon travel at clearly separated rates; wide spatial legibility, strong lateral displacement, coherent perspective, and no flattened backdrop.",dream:"A lucid dream sphere with expressive four-dimensional drift, luminous atmospheric transitions, poetic environmental transformation, and a single unmistakably consistent subject acting as the visual anchor.",sway:"A reversible return-sway movement: travel outward, decelerate, reverse gracefully, and return toward the visual home state with matched composition, identity, rhythm, and spatial continuity."};
document.querySelectorAll("[data-preset]").forEach(b=>b.onclick=()=>{const key=b.dataset.preset,p=presets[key],prompt=$("prompt"),base=prompt.value.split("\\n\\nMotion treatment:")[0].trim();prompt.value=`${base}\\n\\nMotion treatment: ${promptTreatments[key]}`;$("mode").value=p.mode;$("seedLock").value=p.seedLock;$("latentDistance").value=p.shellScale;$("shellCoupling").value=p.shellCoupling;$("cacheThreshold").value=p.cacheThreshold;["dimXY","dimXZ","dimXW","dimYZ","dimYW","dimZW"].forEach((id,i)=>$(id).value=p.rates[i]);document.querySelectorAll(".parameter input,.dimAxis input,#latentDistance").forEach(x=>x.dispatchEvent(new Event("input")));document.querySelectorAll("[data-preset]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");updateJobReady();toast(`${b.querySelector("strong").textContent} prompt generated`)});
function surpriseOrbit(){const keys=Object.keys(presets),key=keys[Math.floor(Math.random()*keys.length)],p=presets[key];$("mode").value=p.mode;$("seedLock").value=Math.max(0,Math.min(.95,p.seedLock+(Math.random()-.5)*.12)).toFixed(2);$("latentDistance").value=Math.max(.01,p.shellScale+(Math.random()-.5)*.18).toFixed(2);$("shellCoupling").value=(p.shellCoupling+(Math.random()-.5)*.3).toFixed(2);$("cacheThreshold").value=p.cacheThreshold;$("seed").value=String(Math.floor(Math.random()*890000000)+10000000);["dimXY","dimXZ","dimXW","dimYZ","dimYW","dimZW"].forEach((id,i)=>$(id).value=(p.rates[i]*(.78+Math.random()*.44)).toFixed(2));document.querySelectorAll(".parameter input,.dimAxis input,#latentDistance").forEach(x=>x.dispatchEvent(new Event("input")));toast(`${key.toUpperCase()} orbit composed · ready to start`);updateJobReady()}
document.querySelectorAll(".groupTitle").forEach(b=>b.onclick=()=>{b.parentElement.classList.toggle("open");b.querySelector("i").textContent=b.parentElement.classList.contains("open")?"−":"+"});
const geometryCopy={elliptic:["ELLIPTIC · CONTROLLED ORBIT","A smooth closed arc around the home identity. Best for stable cinematic motion with gradual change."],omega:["OMEGA / SO(4) · COMPLEX ORBIT","Couples all six rotation planes in four-dimensional latent space. Produces richer viewpoint and form evolution with less predictable motion."],sway:["SWAY · OUT AND RETURN","Moves away from the home state and reverses along a related route. Best for reversible motion and visual return."],oscillatory:["OSCILLATORY · RHYTHMIC PATH","Uses repeating multi-axis waves. Best for cyclical, pulsing, or mechanically rhythmic motion."]},traversalCopy={row_serpentine:"Row serpentine walks each row forward, then reverses the next row to avoid a hard return jump.",column_serpentine:"Column serpentine walks down one column and up the next, favoring vertical neighborhood continuity.",raster:"Raster always moves in one direction and jumps back at each boundary; useful for diagnostics, less smooth for motion."};function updateGeometryHelp(){const g=geometryCopy[$("mode").value];$("geometryName").textContent=g[0];$("geometryHelp").textContent=g[1];$("traversalHelp").textContent=traversalCopy[$("order").value]}$("mode").addEventListener("change",updateGeometryHelp);$("order").addEventListener("change",updateGeometryHelp);
document.querySelectorAll(".parameter input,.dimAxis input,#latentDistance").forEach(input=>input.oninput=()=>{const out=document.querySelector(`output[data-for="${input.id}"]`);if(out)out.value=Number(input.value).toFixed(2);const shell=Math.max(.82,Math.min(1.14,.88+numeric("latentDistance")*.1)),spin=["dimXY","dimXZ","dimXW","dimYZ","dimYW","dimZW"].reduce((n,id)=>n+numeric(id),0)*5;$("sphere").style.setProperty("--shell",shell);$("sphere").style.setProperty("--spin",spin+"deg");$("sphere").style.filter=`drop-shadow(0 0 ${18+numeric("seedLock")*42}px rgba(85,231,238,.24))`});
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-view]").forEach(x=>x.classList.remove("active"));b.classList.add("active");const frame=b.dataset.view==="frame"&&state.frames.length;$("assetStage").style.display=frame?"block":"none";$("sphere").style.display=frame?"none":"block"});
$("focusStage").onclick=()=>{document.querySelector(".workspace").classList.toggle("stageFocused");$("focusStage").textContent=document.querySelector(".workspace").classList.contains("stageFocused")?"↙":"↗";setTimeout(drawMap,350)};
$("indexStart").oninput=updateRange;$("cells").oninput=()=>{$("cellsNumber").value=$("cells").value;updateRange()};$("cellsNumber").oninput=()=>{$("cells").value=Math.max(1,Math.min(65536,numeric("cellsNumber")||1));updateRange()};$("planButton").onclick=renderSeedBatch;$("continueButton").onclick=continueAtlas;$("launchButton").onclick=()=>{if(!state.model.loaded){state.model.pendingPreview=true;$("stageMessage").innerHTML="<strong>LOADING FLUX WORKER</strong><span>The visible prompt will begin as one coherent 32-image GPU batch.</span>";return modelAction(state.model.downloaded?"/api/model/load":"/api/model/download")}submit(false)};$("launchFromPlan").onclick=()=>{$("manifestDialog").close();submit(false)};$("refreshJobs").onclick=refreshJobs;
document.querySelectorAll(".dialogClose,.dialogCloseButton").forEach(b=>b.onclick=()=>$("manifestDialog").close());
$("helpButton").onclick=()=>toast("Plan a coherent latent path, then launch it into the resident FLUX worker.");
$("clearErrors").onclick=async()=>{
  const count=(state.failedJobIds||[]).length;
  if(!count||state.clearing)return;
  state.clearing=true;$("clearErrors").disabled=true;
  try{
    const r=await fetch("/api/jobs/prune",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({keep:0,statuses:["error","cancelled"]})});
    const j=await r.json();
    if(!r.ok||!j.ok)throw Error(j.error||"Could not clear failed jobs");
    toast(`Cleared ${(j.removed||[]).length} failed job${(j.removed||[]).length===1?"":"s"}`);
    refreshJobs();
  }catch(e){toast(e.message)}
  finally{state.clearing=false}
};
