// studies.js
  ["Lanterns Across the Salt Observatory","At blue hour, a solitary white stag crosses a flooded marble observatory suspended above the sea; each measured step sends constellations trembling through reflected water while brass instruments, salt-worn columns, and distant storm light recede in exact cinematic perspective. A continuous lateral tracking shot, anatomically precise, luminous but restrained, quiet awe, coherent physical space, no text or ornament on the animal."],
  ["The Orchard Remembers the Wind","An ancient pear orchard bends beneath a lucid summer storm as a red fox runs between silvered trunks, loose petals and rain moving in layered parallax. Low tracking camera, precise animal anatomy, wet earth reflecting intermittent sky fire, restrained painterly realism, one continuous physical world, stable identity and graceful sequential motion."],
  ["Procession Through the Glass Tides","A small procession of pale horses walks across translucent tidal flats at dawn, their reflections descending into a submerged city of arches and gardens. Slow elevated camera drift, measured hoof movement, atmospheric depth, exact perspective, quiet ceremonial scale, consistent anatomy and identity, continuous cinematic motion without cuts."],
  ["Night Train Beneath the Amber Ice","A midnight train glides beneath a vast ceiling of amber ice while distant forests and signal lamps pass through deep lateral parallax. The camera travels beside one illuminated carriage, frost breathing across its windows, physically coherent reflections, controlled lens compression, patient momentum, elegant sequential continuity."],
  ["The Astronomer’s Mechanical Garden","A lone astronomer walks through a moonlit garden of slowly unfolding brass flowers, glass leaves collecting rain as observatory domes rotate beyond dark cypress trees. Deliberate dolly movement, interlocking foreground and background motion, intricate but stable geometry, subdued gold and indigo light, one continuous dreamlike space."],
  ["River of Quiet Machines","Graceful ceramic machines wade through a shallow black river between monumental concrete pylons, sending precise concentric ripples through reflected clouds. Wide cinematic tracking, controlled mechanical articulation, deep environmental parallax, soft overcast luminance, consistent forms, solemn and physically coherent motion."],
  ["The Blue Heron and the Falling City","A blue heron flies steadily above terraced rooftops descending through morning fog toward an immense inland sea, laundry lines, antennas, trees, and stone balconies sliding below in distinct depth layers. Stable bird anatomy, fluid wing cycles, aerial tracking camera, luminous realism and uninterrupted spatial continuity."],
  ["After Rain in the Copper Arcade","A dark mare moves at a measured canter through a long copper arcade after rain, warm shop light folding across the pavement as columns, hanging gardens, and distant pedestrians pass in elegant parallax. Ground-level tracking, precise anatomy, restrained cinematic color, consistent identity, no rider or tack, continuous motion."]
];
function seedPage(){const saved=[sessionStorage.getItem("motionAtlasTitle"),sessionStorage.getItem("motionAtlasPrompt"),sessionStorage.getItem("motionAtlasSeed")];if(saved.every(Boolean)){[$("id").value,$("prompt").value,$("seed").value]=saved;return}const bytes=new Uint32Array(2);crypto.getRandomValues(bytes);const index=bytes[0]%pageStudies.length,study=pageStudies[index],seed=String(10000000+bytes[1]%890000000);$("id").value=study[0];$("prompt").value=study[1];$("seed").value=seed;sessionStorage.setItem("motionAtlasTitle",study[0]);sessionStorage.setItem("motionAtlasPrompt",study[1]);sessionStorage.setItem("motionAtlasSeed",seed)}
const numeric=id=>Number($(id).value);
