const $=id=>document.getElementById(id);
const state={runType:"path",activeJob:null,started:0,frames:[],assetSide:"A",gpuProcesses:new Map(),preview:new Map(),selectedFlavor:null};
const numeric=id=>Number($(id).value);
function toast(message){$("toast").textContent=message;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2600)}
function checkpoint(name,status="done"){const row=document.querySelector(`[data-step="${name}"]`);if(!row)return;row.classList.remove("active","done");row.classList.add(status);$("spineState").textContent=status==="active"?name.toUpperCase():"LIVE"}
function drawMap(){
  const c=$("mapCanvas"),d=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*d;c.height=r.height*d;
  const x=c.getContext("2d");x.scale(d,d);x.strokeStyle="#55e7ee22";x.lineWidth=.7;
  for(let i=0;i<18;i++){x.beginPath();x.ellipse(r.width/2,r.height/2,r.width*(.12+i*.027),r.height*(.42-i*.009),0,0,Math.PI*2);x.stroke()}
  for(let i=0;i<15;i++){x.beginPath();x.moveTo(i*r.width/14,0);x.quadraticCurveTo(r.width/2,r.height/2,(14-i)*r.width/14,r.height);x.stroke()}
}
function updateRange(){
  const start=numeric("indexStart"),cells=numeric("cells"),end=Math.min(65536,start+cells);
  $("indexStartOut").value=start.toLocaleString();$("cellsOut").value=`${cells.toLocaleString()} cells`;
  $("rangeLabel").value=`${start.toLocaleString()}—${end.toLocaleString()}`;$("progressText").textContent=`0 / ${cells.toLocaleString()}`;
  document.querySelector(".mapCursor").style.top=`${Math.min(94,start/65536*100)}%`;
}
function payload(dryRun=false){const start=numeric("indexStart"),cells=numeric("cells");return{
  prompt:$("prompt").value.trim(),id:$("id").value.trim(),backend:$("backend").value,model:$("model").value,precision:$("precision").value,batch_size:numeric("batchSize"),run_type:state.runType,
  index_start:start,index_end:Math.min(65536,start+cells),sample_mode:state.runType==="path"?"contiguous":"nested_sparse",cells,
  size:numeric("size"),steps:numeric("steps"),guidance:numeric("guidance"),seed:$("seed").value,
  shell_scale:numeric("shellScale"),seed_lock:numeric("seedLock"),shell_coupling:numeric("shellCoupling"),
  mode:$("mode").value,traversal_order:$("order").value,dimension_rates:["dimXY","dimXZ","dimXW","dimYZ","dimYW","dimZW"].map(numeric),adapter:$("adapter").value,
  cache_threshold:numeric("cacheThreshold"),cache_downsample:1,cache_warmup:numeric("cacheWarmup"),dry_run:dryRun}}
async function submit(dryRun){
  const body=payload(dryRun);if(!body.prompt){toast("A motion prompt is required");return}
  const button=dryRun?$("planButton"):$("launchButton");button.disabled=true;
  try{const r=await fetch("/api/atlas/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||"Atlas request failed");
    if(dryRun)showManifest(j.plan);else{state.activeJob=j.job?.id||j.plan?.id;state.started=Date.now();checkpoint("planned");checkpoint("dispatched");if(j.nexus?.ok)checkpoint("nexus");else checkpoint("nexus","active");checkpoint("producing","active");$("productionSummary").textContent=`0 / ${Number(j.plan?.cells||0).toLocaleString()} cells · starting now`;$("progressText").textContent=`0 / ${Number(j.plan?.cells||0).toLocaleString()}`;$("progressBar").style.width="0%";$("stageMessage").innerHTML="<strong>ATLAS IN MOTION</strong><span>The resident worker is traversing the planned sphere.</span>";toast("Atlas queued on "+String(j.plan?.backend||"worker").toUpperCase())}
  }catch(e){toast(e.message)}finally{button.disabled=false}
}
async function previewFlavors(){const prompt=$("prompt").value.trim();if(!prompt){toast("A motion prompt is required");return}state.preview.clear();state.selectedFlavor=null;$("previewGrid").innerHTML=Array.from({length:32},()=>'<div class="flavorPending"></div>').join("");$("previewStatus").textContent="Dispatching 32 unique seeds";$("previewCount").textContent="0 / 32";$("previewProgressBar").style.width="0%";$("launchFlavor").disabled=true;$("previewDialog").showModal();checkpoint("planned","active");const base=String(Date.now()%800000000+10000000);try{const r=await fetch("/api/render",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,model:"dev",backend:$("backend").value,width:384,height:384,steps:12,guidance:numeric("guidance"),seed:base,filename:`atlas-flavor-${Date.now()}.png`,iterations:32})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||"Preview batch failed");(j.jobs||[]).forEach((job,i)=>state.preview.set(job.id,{seed:String(j.plans?.[i]?.seed??Number(base)+i),job}));$("previewStatus").textContent="Generating flavor batch on the resident FLUX worker";checkpoint("planned")}catch(e){$("previewStatus").textContent=e.message;toast(e.message)}}
function updatePreview(jobs){if(!state.preview.size)return;for(const job of jobs){const item=state.preview.get(job.id);if(item)item.job=job}const ready=[...state.preview.values()].filter(x=>x.job.output_url&&String(x.job.status).toLowerCase()==="done");$("previewCount").textContent=`${ready.length} / 32`;$("previewProgressBar").style.width=`${ready.length/32*100}%`;$("previewStatus").textContent=ready.length===32?"Select one flavor to anchor the atlas":`Generating flavor ${Math.min(32,ready.length+1)} of 32`;$("previewGrid").innerHTML=[...state.preview.values()].map(x=>x.job.output_url?`<button class="flavor ${state.selectedFlavor?.seed===x.seed?"selected":""}" data-seed="${x.seed}"><img src="${escapeHTML(x.job.output_url)}" alt="Seed ${x.seed}"><span>SEED ${x.seed}</span></button>`:'<div class="flavorPending"></div>').join("");document.querySelectorAll(".flavor").forEach(b=>b.onclick=()=>{state.selectedFlavor={seed:b.dataset.seed,url:b.querySelector("img").src};$("seed").value=b.dataset.seed;document.querySelectorAll(".flavor").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");$("launchFlavor").disabled=false;$("launchButton").disabled=false;$("launchButton").querySelector("span").textContent="Launch selected flavor";$("previewStatus").textContent=`Seed ${b.dataset.seed} selected · ready for full atlas`})}
function showManifest(p){const entries=[["Backend",p.backend],["Sequence",`${p.cells} cells`],["Frame",`${p.width}² / ${p.steps} steps`],["Orbit",p.mode],["Traversal",p.traversal_order],["Cache",`${p.adapter} / ${p.cache_threshold}`]];
  entries.splice(1,0,["Model",`FLUX.1 Dev / ${p.precision||"BF16"}`],["Batch",p.batch_size||1]);
  checkpoint("planned");$("manifest").innerHTML=entries.map(([k,v])=>`<div class="manifestItem"><span>${k}</span><strong>${v}</strong></div>`).join("")+`<div class="manifestItem manifestPrompt"><span>Motion direction</span><strong>${escapeHTML(p.prompt)}</strong></div>`;$("manifestDialog").showModal()}
function escapeHTML(s){const d=document.createElement("div");d.textContent=s??"";return d.innerHTML}
function renderGPU(g){if(!g)return;$("gpuName").textContent=g.name;$("device").textContent=`CUDA · ${g.name.replace(/^NVIDIA /,"")}`;const memPct=g.memory_total?g.memory_used/g.memory_total*100:0,powerPct=g.power_limit?g.power_draw/g.power_limit*100:0;$("vramValue").textContent=`${(g.memory_used/1024).toFixed(1)} / ${(g.memory_total/1024).toFixed(0)} GB`;$("vramBar").style.width=Math.min(100,memPct)+"%";$("computeValue").textContent=Math.round(g.utilization)+"%";$("computeBar").style.width=Math.min(100,g.utilization)+"%";$("thermalValue").textContent=Math.round(g.temperature)+"°";$("powerValue").textContent=`${Math.round(g.power_draw)} W · ${Math.round(powerPct)}%`}
function renderGPUProcess(p){state.gpuProcesses.set(p.pid,p);$("gpuProcesses").innerHTML=[...state.gpuProcesses.values()].sort((a,b)=>b.memory_used-a.memory_used).map(x=>`<div class="gpuProcess ${String(x.label).toLowerCase()}" title="${escapeHTML(x.command)}"><b>${escapeHTML(x.label)}</b><span>PID ${x.pid}</span><strong>${(Number(x.memory_used)/1024).toFixed(1)} GB</strong><span>SM ${Math.round(Number(x.sm))}%</span></div>`).join("")}
function renderModel(m){$("downloadState").textContent=m.downloaded?"READY":m.downloading?"DOWNLOADING":"NOT FOUND";$("loadState").textContent=m.loaded?"RESIDENT":"NOT LOADED";$("downloadDot").classList.toggle("on",!!m.downloaded);$("loadDot").classList.toggle("on",!!m.loaded);$("downloadModel").disabled=!!m.downloaded||!!m.downloading;$("loadModel").disabled=!m.downloaded||!!m.loaded;$("modelProgressBar").classList.toggle("busy",!!m.downloading||(!m.loaded&&$("loadModel").disabled&&m.downloaded));$("modelProgressBar").style.width=m.loaded?"100%":m.downloaded&&!m.downloading?"62%":"";$("modelMessage").textContent=m.message||m.device||(m.loaded?"Model is resident on the GPU.":m.downloaded?"BF16 weights are ready to load.":"FLUX.1 Dev weights are not on disk.");if(m.loaded){checkpoint("model");checkpoint("worker")}}
function showJobProgress(job){if(!job)return;state.activeJob=job.id;const done=Number(job.atlas_done??job.step??0),total=Number(job.atlas_total??job.total_steps??numeric("cells")),pct=total?Math.min(100,done/total*100):0;$("studyName").textContent=String(job.id||"MOTION ATLAS").replace(/^spheremap_atlas_/,"").replaceAll("_"," ").toUpperCase();$("experimentPhase").textContent=`${String(job.status||"queued").toUpperCase()} · ${String(job.phase||"WAITING").toUpperCase()}`;$("progressText").textContent=`${done.toLocaleString()} / ${total.toLocaleString()}`;$("progressBar").style.width=pct+"%";$("productionSummary").textContent=`${done.toLocaleString()} / ${total.toLocaleString()} cells · ${String(job.phase||job.status)}`;if(["running"].includes(String(job.status).toLowerCase()))checkpoint("producing","active");if(done>=total&&total>0)checkpoint("producing");if(job.cells_per_hour)$("rate").textContent=(Number(job.cells_per_hour)/3600).toFixed(2)+" fps";if(job.eta_seconds)$("eta").textContent=(Number(job.eta_seconds)/60).toFixed(1)+" min";if(job.cache_hit_rate!=null)$("cacheState").textContent=`XFRAME / ${Math.round(Number(job.cache_hit_rate)*100)}% HIT`}
function renderJobFeed(j){const allJobs=j.jobs||[];updatePreview(allJobs);const jobs=allJobs.filter(x=>String(x.kind||"")==="atlas_sphere"||x.viewer_url);$("workerState").textContent=j.worker_running?"WORKER LIVE":"SUITE LIVE";const active=jobs.find(x=>["running","queued","cancelling"].includes(String(x.status).toLowerCase()))||jobs.find(x=>x.id===state.activeJob);showJobProgress(active);$("sessions").innerHTML=jobs.length?jobs.slice(0,6).map(x=>`<button class="session ${x.id===state.activeJob?"active":""}" data-job="${escapeHTML(x.id)}"><span>${escapeHTML(x.id)}</span><small>${escapeHTML(x.status||"queued")} · ${Number(x.atlas_done??x.step??0).toLocaleString()} / ${Number(x.atlas_total??x.total_steps??0).toLocaleString()}</small></button>`).join(""):'<div class="session empty"><span>NO ACTIVE RUNS</span><small>Launch an atlas to begin</small></div>';document.querySelectorAll("[data-job]").forEach(b=>b.onclick=()=>{state.activeJob=b.dataset.job;showJobProgress(jobs.find(x=>x.id===state.activeJob))})}
async function refreshJobs(){try{const r=await fetch("/api/jobs"),j=await r.json();renderJobFeed(j)}catch{}}
function connectStreams(){const jobs=new EventSource("/api/jobs/events");jobs.addEventListener("jobs",e=>{try{renderJobFeed(JSON.parse(e.data))}catch{}});jobs.onerror=()=>{$("workerState").textContent="RECONNECTING"};const gpu=new EventSource("/api/telemetry/events");gpu.addEventListener("gpu",e=>{try{renderGPU(JSON.parse(e.data).gpu)}catch{}});gpu.onerror=()=>{$("computeValue").textContent="RECONNECTING"};const processes=new EventSource("/api/telemetry/processes/events");processes.addEventListener("process",e=>{try{renderGPUProcess(JSON.parse(e.data))}catch{}});const assets=new EventSource("/api/assets/events");assets.addEventListener("asset",e=>{try{const event=JSON.parse(e.data);if(state.activeJob&&event.job_id!==state.activeJob)return;const a=event.asset||{};ingestFrame({url:a.access_url,index:a.index,completed:Number(a.index)+1})}catch{}});assets.onerror=()=>{$("stageMessage").querySelector("span").textContent="Piper reconnecting to the asset socket."};const model=new EventSource("/api/model/events");model.addEventListener("model",e=>{try{renderModel(JSON.parse(e.data))}catch{}})}
async function modelAction(path){try{const r=await fetch(path,{method:"POST"}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||"Model action failed");$("modelMessage").textContent=String(j.status||"Working").toUpperCase();$("modelProgressBar").classList.add("busy")}catch(e){toast(e.message)}}
function ingestFrame(d){const url=d.url||d.output_url||d.image_url;if(url&&!state.frames.includes(url)){state.frames.push(url);checkpoint("assets");$("assetSummary").textContent=`${state.frames.length.toLocaleString()} assets received from Piper`;const next=state.assetSide==="A"?$("assetFrameA"):$("assetFrameB"),prior=state.assetSide==="A"?$("assetFrameB"):$("assetFrameA");next.src=url;next.onload=()=>{prior.classList.remove("active");next.classList.add("active")};state.assetSide=state.assetSide==="A"?"B":"A";$("assetStage").style.display="block";$("sphere").style.display="none";$("stageMessage").style.display="none";const img=document.createElement("img");img.src=url;$("filmstrip").querySelector(".filmEmpty")?.remove();$("filmstrip").appendChild(img);$("filmstrip").scrollLeft=999999}
  const done=Number(d.completed??d.index??state.frames.length),total=numeric("cells"),pct=Math.min(100,done/total*100);$("progressBar").style.width=pct+"%";$("progressText").textContent=`${done.toLocaleString()} / ${total.toLocaleString()}`;$("currentCell").textContent=String(d.cell??d.index??done).padStart(5,"0");if(state.started&&done){const fps=done/((Date.now()-state.started)/1000);$("rate").textContent=fps.toFixed(2)+" fps";$("eta").textContent=Math.max(0,(total-done)/fps/60).toFixed(1)+" min"}}
document.querySelectorAll("[data-run]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-run]").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.runType=b.dataset.run});
document.querySelectorAll(".groupTitle").forEach(b=>b.onclick=()=>{b.parentElement.classList.toggle("open");b.querySelector("i").textContent=b.parentElement.classList.contains("open")?"−":"+"});
document.querySelectorAll(".parameter input,.dimAxis input").forEach(input=>input.oninput=()=>{const out=document.querySelector(`output[data-for="${input.id}"]`);if(out)out.value=Number(input.value).toFixed(2);const shell=Math.max(.82,Math.min(1.14,.88+numeric("shellScale")*.1)),spin=["dimXY","dimXZ","dimXW","dimYZ","dimYW","dimZW"].reduce((n,id)=>n+numeric(id),0)*5;$("sphere").style.setProperty("--shell",shell);$("sphere").style.setProperty("--spin",spin+"deg");$("sphere").style.filter=`drop-shadow(0 0 ${18+numeric("seedLock")*42}px rgba(85,231,238,.24))`});
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-view]").forEach(x=>x.classList.remove("active"));b.classList.add("active");const frame=b.dataset.view==="frame"&&state.frames.length;$("assetStage").style.display=frame?"block":"none";$("sphere").style.display=frame?"none":"block"});
$("focusStage").onclick=()=>{document.querySelector(".workspace").classList.toggle("stageFocused");$("focusStage").textContent=document.querySelector(".workspace").classList.contains("stageFocused")?"↙":"↗";setTimeout(drawMap,350)};
$("indexStart").oninput=updateRange;$("cells").oninput=()=>{$("cellsNumber").value=$("cells").value;updateRange()};$("cellsNumber").oninput=()=>{$("cells").value=Math.max(1,Math.min(65536,numeric("cellsNumber")||1));updateRange()};$("planButton").onclick=previewFlavors;$("launchButton").onclick=()=>submit(false);$("launchFromPlan").onclick=()=>{$("manifestDialog").close();submit(false)};$("launchFlavor").onclick=()=>{$("previewDialog").close();submit(false)};$("refreshJobs").onclick=refreshJobs;
document.querySelectorAll(".dialogClose,.dialogCloseButton").forEach(b=>b.onclick=()=>$("manifestDialog").close());
document.querySelectorAll(".previewClose,.previewCloseButton").forEach(b=>b.onclick=()=>$("previewDialog").close());
$("helpButton").onclick=()=>toast("Plan a coherent latent path, then launch it into the resident FLUX worker.");
$("downloadModel").onclick=()=>modelAction("/api/model/download");$("loadModel").onclick=()=>modelAction("/api/model/load");
drawMap();updateRange();connectStreams();window.addEventListener("resize",drawMap);
