const $=id=>document.getElementById(id);
const state={runType:"path",activeJob:null,started:0,frames:[],assetSide:"A",acceptedAssetJobs:new Set(),pendingAssets:new Map(),gpuProcesses:new Map(),preview:new Map(),selectedFlavor:null,model:{known:false,downloaded:false,loaded:false,pendingPreview:true},discovery:{started:false,stopped:false,level:0,jobs:new Map(),ready:new Set()}};
const pageStudies=[
  ["Lanterns Across the Salt Observatory","At blue hour, a solitary white stag crosses a flooded marble observatory suspended above the sea; each measured step sends constellations trembling through reflected water while brass instruments, salt-worn columns, and distant storm light recede in exact cinematic perspective. A continuous lateral tracking shot, anatomically precise, luminous but restrained, quiet awe, coherent physical space, no text or ornament on the animal."],
  ["The Orchard Remembers the Wind","An ancient pear orchard bends beneath a lucid summer storm as a red fox runs between silvered trunks, loose petals and rain moving in layered parallax. Low tracking camera, precise animal anatomy, wet earth reflecting intermittent sky fire, restrained painterly realism, one continuous physical world, stable identity and graceful sequential motion."],
  ["Procession Through the Glass Tides","A small procession of pale horses walks across translucent tidal flats at dawn, their reflections descending into a submerged city of arches and gardens. Slow elevated camera drift, measured hoof movement, atmospheric depth, exact perspective, quiet ceremonial scale, consistent anatomy and identity, continuous cinematic motion without cuts."],
  ["Night Train Beneath the Amber Ice","A midnight train glides beneath a vast ceiling of amber ice while distant forests and signal lamps pass through deep lateral parallax. The camera travels beside one illuminated carriage, frost breathing across its windows, physically coherent reflections, controlled lens compression, patient momentum, elegant sequential continuity."],
  ["The Astronomer’s Mechanical Garden","A lone astronomer walks through a moonlit garden of slowly unfolding brass flowers, glass leaves collecting rain as observatory domes rotate beyond dark cypress trees. Deliberate dolly movement, interlocking foreground and background motion, intricate but stable geometry, subdued gold and indigo light, one continuous dreamlike space."],
  ["River of Quiet Machines","Graceful ceramic machines wade through a shallow black river between monumental concrete pylons, sending precise concentric ripples through reflected clouds. Wide cinematic tracking, controlled mechanical articulation, deep environmental parallax, soft overcast luminance, consistent forms, solemn and physically coherent motion."],
  ["The Blue Heron and the Falling City","A blue heron flies steadily above terraced rooftops descending through morning fog toward an immense inland sea, laundry lines, antennas, trees, and stone balconies sliding below in distinct depth layers. Stable bird anatomy, fluid wing cycles, aerial tracking camera, luminous realism and uninterrupted spatial continuity."],
  ["After Rain in the Copper Arcade","A dark mare moves at a measured canter through a long copper arcade after rain, warm shop light folding across the pavement as columns, hanging gardens, and distant pedestrians pass in elegant parallax. Ground-level tracking, precise anatomy, restrained cinematic color, consistent identity, no rider or tack, continuous motion."]
];
function seedPage(){const bytes=new Uint32Array(2);crypto.getRandomValues(bytes),last=Number(sessionStorage.getItem("motionAtlasStudy"));let index=bytes[0]%pageStudies.length;if(Number.isInteger(last)&&index===last)index=(index+1+bytes[1]%(pageStudies.length-1))%pageStudies.length;sessionStorage.setItem("motionAtlasStudy",String(index));const study=pageStudies[index];$("id").value=study[0];$("prompt").value=study[1];$("seed").value=String(10000000+bytes[1]%890000000)}
const numeric=id=>Number($(id).value);
function toast(message){$("toast").textContent=message;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2600)}
function acceptAssetJob(id){if(!id)return;state.acceptedAssetJobs.add(id);for(const event of state.pendingAssets.get(id)||[])ingestAssetEvent(event);state.pendingAssets.delete(id)}
function ingestAssetEvent(event){const a=event.asset||{};ingestFrame({url:a.access_url,index:a.index,seed:a.seed,total:Number(a.total)||0,updateProgress:!!state.activeJob&&event.job_id===state.activeJob})}
function checkpoint(name,status="done"){const row=document.querySelector(`[data-step="${name}"]`);if(!row)return;row.classList.remove("active","done");if(status)row.classList.add(status);$("spineState").textContent=status==="active"?name.toUpperCase():status==="done"?"LIVE":"INCOMPLETE"}
function updateJobReady(){const configured=$("prompt").value.trim()&&$("id").value.trim()&&numeric("cells")>0&&numeric("batchSize")>0&&numeric("size")>0&&numeric("steps")>0&&numeric("guidance")>0,loaded=state.model.loaded;checkpoint("planned",configured?"done":"");$("planButton").disabled=!loaded||!configured;$("launchButton").disabled=state.model.known&&loaded&&!configured;$("launchButton").querySelector("span").textContent=!state.model.known?"Checking worker":!loaded?(state.model.downloaded?"Load worker":"Download model"):configured?"Start atlas":"Complete setup";return !!configured&&loaded}
function drawMap(){
  const c=$("mapCanvas"),d=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*d;c.height=r.height*d;
  const x=c.getContext("2d");x.scale(d,d);x.strokeStyle="#55e7ee22";x.lineWidth=.7;
  for(let i=0;i<18;i++){x.beginPath();x.ellipse(r.width/2,r.height/2,r.width*(.12+i*.027),r.height*(.42-i*.009),0,0,Math.PI*2);x.stroke()}
  for(let i=0;i<15;i++){x.beginPath();x.moveTo(i*r.width/14,0);x.quadraticCurveTo(r.width/2,r.height/2,(14-i)*r.width/14,r.height);x.stroke()}
}
function updateRange(){
  const start=numeric("indexStart"),cells=numeric("cells"),end=Math.min(65536,start+cells);
  $("indexStartOut").value=start.toLocaleString();$("cellsOut").value=`${cells.toLocaleString()} cells`;
  $("rangeLabel").value=`${start.toLocaleString()}—${end.toLocaleString()}`;$("progressText").textContent=`0 / ${cells.toLocaleString()}`;
  document.querySelector(".mapCursor").style.top=`${Math.min(94,start/65536*100)}%`;
}
function payload(dryRun=false){const start=numeric("indexStart"),cells=numeric("cells");return{
  prompt:$("prompt").value.trim(),id:$("id").value.trim(),backend:$("backend").value,model:$("model").value,precision:$("precision").value,batch_size:numeric("batchSize"),run_type:state.runType,
  index_start:start,index_end:Math.min(65536,start+cells),sample_mode:state.runType==="path"?"contiguous":"nested_sparse",cells,
  size:numeric("size"),steps:numeric("steps"),guidance:numeric("guidance"),seed:$("seed").value,
  shell_scale:numeric("latentDistance"),seed_lock:numeric("seedLock"),shell_coupling:numeric("shellCoupling"),
  mode:$("mode").value,traversal_order:$("order").value,dimension_rates:["dimXY","dimXZ","dimXW","dimYZ","dimYW","dimZW"].map(numeric),adapter:$("adapter").value,
  cache_threshold:numeric("cacheThreshold"),cache_downsample:1,cache_warmup:numeric("cacheWarmup"),dry_run:dryRun}}
async function submit(dryRun){
  if(!state.model.loaded){toast("Load the FLUX worker before starting");return}
  const body=payload(dryRun);if(!body.prompt){toast("A motion prompt is required");return}
  if(!dryRun)state.discovery.stopped=true;
  const button=dryRun?$("planButton"):$("launchButton");button.disabled=true;
  try{const r=await fetch("/api/atlas/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||"Atlas request failed");
    if(dryRun)showManifest(j.plan);else{state.activeJob=j.job?.id||j.plan?.id;acceptAssetJob(state.activeJob);state.started=Date.now();checkpoint("planned");checkpoint("dispatched");if(j.nexus?.ok)checkpoint("nexus");else checkpoint("nexus","active");checkpoint("producing","active");$("productionSummary").textContent=`0 / ${Number(j.plan?.cells||0).toLocaleString()} cells · starting now`;$("progressText").textContent=`0 / ${Number(j.plan?.cells||0).toLocaleString()}`;$("progressBar").style.width="0%";$("stageMessage").innerHTML="<strong>ATLAS IN MOTION</strong><span>The resident worker is traversing the planned sphere.</span>";toast("Atlas queued on "+String(j.plan?.backend||"worker").toUpperCase())}
  }catch(e){toast(e.message)}finally{button.disabled=false}
}
async function previewFlavors(){const prompt=$("prompt").value.trim();if(!prompt){toast("A motion prompt is required");return}state.preview.clear();state.selectedFlavor=null;$("previewGrid").innerHTML=Array.from({length:32},()=>'<div class="flavorPending"></div>').join("");$("previewStatus").textContent="Dispatching 32 unique seeds";$("previewCount").textContent="0 / 32";$("previewProgressBar").style.width="0%";$("launchFlavor").disabled=true;$("previewDialog").showModal();checkpoint("planned");const base=String(Date.now()%800000000+10000000);try{const r=await fetch("/api/render",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,model:"dev",backend:$("backend").value,width:384,height:384,steps:12,guidance:numeric("guidance"),seed:base,filename:`atlas-flavor-${Date.now()}.png`,iterations:32})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||"Preview batch failed");(j.jobs||[]).forEach((job,i)=>state.preview.set(job.id,{seed:String(j.plans?.[i]?.seed??Number(base)+i),job}));$("previewStatus").textContent="Generating flavor batch on the resident FLUX worker";checkpoint("planned")}catch(e){$("previewStatus").textContent=e.message;toast(e.message)}}
async function renderSeedBatch(){if(!state.model.loaded){toast("Load the FLUX worker before generating previews");return}const prompt=$("prompt").value.trim();if(!prompt){toast("A motion prompt is required");return}const button=$("planButton"),base=String(Date.now()%800000000+10000000);button.disabled=true;button.textContent="Dispatching 1·2·4·8·16…";try{const r=await fetch("/api/atlas/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,model:"dev",backend:$("backend").value,width:numeric("size"),height:numeric("size"),steps:numeric("steps"),guidance:numeric("guidance"),latent_distance:numeric("latentDistance"),seed:base,filename:`seed-ramp-${Date.now()}.png`})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||"Preview batch failed");if(j.job?.id)acceptAssetJob(j.job.id);checkpoint("dispatched");checkpoint("nexus",j.nexus?.ok?"done":"active");$("assetSummary").textContent="Continuity sequence queued · 1 → 2 → 4 → 8 → 16";toast("Continuous latent sequence is running")}catch(e){toast(e.message)}finally{button.textContent="Preview 1·2·4·8·16";updateJobReady()}}
function updatePreview(jobs){if(!state.preview.size)return;for(const job of jobs){const item=state.preview.get(job.id);if(item)item.job=job}const ready=[...state.preview.values()].filter(x=>x.job.output_url&&String(x.job.status).toLowerCase()==="done");$("previewCount").textContent=`${ready.length} / 32`;$("previewProgressBar").style.width=`${ready.length/32*100}%`;$("previewStatus").textContent=ready.length===32?"Select one flavor to anchor the atlas":`Generating flavor ${Math.min(32,ready.length+1)} of 32`;$("previewGrid").innerHTML=[...state.preview.values()].map(x=>x.job.output_url?`<button class="flavor ${state.selectedFlavor?.seed===x.seed?"selected":""}" data-seed="${x.seed}"><img src="${escapeHTML(x.job.output_url)}" alt="Seed ${x.seed}"><span>SEED ${x.seed}</span></button>`:'<div class="flavorPending"></div>').join("");document.querySelectorAll(".flavor").forEach(b=>b.onclick=()=>{state.selectedFlavor={seed:b.dataset.seed,url:b.querySelector("img").src};$("seed").value=b.dataset.seed;document.querySelectorAll(".flavor").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");$("launchFlavor").disabled=false;$("launchButton").disabled=false;$("launchButton").querySelector("span").textContent="Launch selected flavor";$("previewStatus").textContent=`Seed ${b.dataset.seed} selected · ready for full atlas`})}
async function startDiscoveryBatch(){
  const d=state.discovery;if(d.stopped||d.level>=7||d.jobs.size)return;
  const count=2**d.level++,prompt=$("prompt").value.trim();if(!prompt){d.started=false;return}
  $("stageMessage").innerHTML=`<strong>DISCOVERY STREAM · ${count}</strong><span>Generating a ${count}-image seed batch while you shape the atlas.</span>`;
  const base=String(Date.now()%800000000+10000000);
  try{const r=await fetch("/api/render",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,model:"dev",backend:$("backend").value,width:384,height:384,steps:12,guidance:numeric("guidance"),seed:base,filename:`atlas-discovery-${Date.now()}.png`,iterations:count})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||"Discovery batch failed");(j.jobs||[]).forEach((job,i)=>d.jobs.set(job.id,{seed:String(j.plans?.[i]?.seed??Number(base)+i),job}));$("assetSummary").textContent=`Discovery batch ${count} queued · Piper standing by`}catch(e){d.started=false;$("stageMessage").innerHTML=`<strong>DISCOVERY PAUSED</strong><span>${escapeHTML(e.message)}</span>`}
}
function updateDiscovery(jobs){
  const d=state.discovery;if(!d.started||d.stopped)return;
  for(const job of jobs){const item=d.jobs.get(job.id);if(!item)continue;item.job=job;if(job.output_url&&String(job.status).toLowerCase()==="done"&&!d.ready.has(job.id)){d.ready.add(job.id);ingestFrame({url:job.output_url,seed:item.seed,discovery:true})}}
  if(d.jobs.size&&[...d.jobs.values()].every(x=>["done","error","cancelled"].includes(String(x.job.status).toLowerCase()))){d.jobs.clear();d.ready.clear();startDiscoveryBatch()}
}
function showManifest(p){const entries=[["Backend",p.backend],["Sequence",`${p.cells} cells`],["Frame",`${p.width}² / ${p.steps} steps`],["Orbit",p.mode],["Traversal",p.traversal_order],["Cache",`${p.adapter} / ${p.cache_threshold}`]];
  entries.splice(1,0,["Model",`FLUX.1 Dev / ${p.precision||"BF16"}`],["Batch",p.batch_size||1]);
  checkpoint("planned");$("manifest").innerHTML=entries.map(([k,v])=>`<div class="manifestItem"><span>${k}</span><strong>${v}</strong></div>`).join("")+`<div class="manifestItem manifestPrompt"><span>Motion direction</span><strong>${escapeHTML(p.prompt)}</strong></div>`;$("manifestDialog").showModal()}
function escapeHTML(s){const d=document.createElement("div");d.textContent=s??"";return d.innerHTML}
function renderGPU(g){if(!g)return;$("gpuName").textContent=g.name;$("device").textContent=`CUDA · ${g.name.replace(/^NVIDIA /,"")}`;const memPct=g.memory_total?g.memory_used/g.memory_total*100:0,powerPct=g.power_limit?g.power_draw/g.power_limit*100:0;$("vramValue").textContent=`${(g.memory_used/1024).toFixed(1)} / ${(g.memory_total/1024).toFixed(0)} GB`;$("vramBar").style.width=Math.min(100,memPct)+"%";$("computeValue").textContent=Math.round(g.utilization)+"%";$("computeBar").style.width=Math.min(100,g.utilization)+"%";$("thermalValue").textContent=Math.round(g.temperature)+"°";$("powerValue").textContent=`${Math.round(g.power_draw)} W · ${Math.round(powerPct)}%`}
function renderGPUProcess(p){state.gpuProcesses.set(p.pid,p);$("gpuProcesses").innerHTML=[...state.gpuProcesses.values()].sort((a,b)=>b.memory_used-a.memory_used).map(x=>`<div class="gpuProcess ${String(x.label).toLowerCase()}" title="${escapeHTML(x.command)}"><b>${escapeHTML(x.label)}</b><span>PID ${x.pid}</span><strong>${(Number(x.memory_used)/1024).toFixed(1)} GB</strong><span>SM ${Math.round(Number(x.sm))}%</span></div>`).join("")}
function renderModel(m){const pendingPreview=state.model.pendingPreview,justLoaded=!state.model.loaded&&!!m.loaded;state.model={known:true,downloaded:!!m.downloaded,loaded:!!m.loaded,pendingPreview};$("downloadState").textContent=m.downloaded?"READY":m.downloading?"DOWNLOADING":"NOT FOUND";$("loadState").textContent=m.loaded?"RESIDENT":"NOT LOADED";$("downloadDot").classList.toggle("on",!!m.downloaded);$("loadDot").classList.toggle("on",!!m.loaded);$("downloadModel").disabled=!!m.downloaded||!!m.downloading;$("loadModel").disabled=!m.downloaded||!!m.loaded;$("modelProgressBar").classList.toggle("busy",!!m.downloading);$("modelProgressBar").style.width=m.loaded?"100%":m.downloaded&&!m.downloading?"62%":"";$("modelMessage").textContent=m.message||m.device||(m.loaded?"Model is resident on the GPU.":m.downloaded?"BF16 weights are ready. Load the worker to continue.":"FLUX.1 Dev weights are not on disk.");const top=$("modelTopState");top.className="modelTopState "+(m.loaded?"loaded":m.downloaded?"downloaded":"");top.lastChild.textContent=m.loaded?" MODEL LOADED":m.downloaded?" LOAD WORKER":" MODEL MISSING";checkpoint("model",m.loaded?"done":"");checkpoint("worker",m.loaded?"done":"");if(!m.loaded&&state.frames.length===0){$("stageMessage").style.display="grid";$("stageMessage").innerHTML="<strong>FLUX WORKER NOT LOADED</strong><span>Load the resident worker before generating previews or starting the atlas.</span>"}updateJobReady();if(justLoaded&&pendingPreview){state.model.pendingPreview=false;renderSeedBatch()}}
function showJobProgress(job){if(!job)return;state.activeJob=job.id;const preview=String(job.kind||"")==="seed_preview",done=Number(preview?job.images_done:(job.atlas_done??job.step??0)),total=Number(preview?job.images_total:(job.atlas_total??job.total_steps??0)),pct=total?Math.min(100,done/total*100):0;$("experimentPhase").textContent=`${String(job.status||"queued").toUpperCase()} · ${String(job.phase||"WAITING").toUpperCase()}`;$("progressText").textContent=total?`${done.toLocaleString()} / ${total.toLocaleString()}`:"— / —";$("progressBar").style.width=pct+"%";$("productionSummary").textContent=total?`${done.toLocaleString()} / ${total.toLocaleString()} ${preview?"images":"cells"} · ${String(job.phase||job.status)}`:String(job.phase||job.status);if(["running"].includes(String(job.status).toLowerCase()))checkpoint("producing","active");if(done>=total&&total>0)checkpoint("producing");if(job.cells_per_hour)$("rate").textContent=(Number(job.cells_per_hour)/3600).toFixed(2)+" fps";if(job.eta_seconds)$("eta").textContent=(Number(job.eta_seconds)/60).toFixed(1)+" min";if(job.cache_hit_rate!=null)$("cacheState").textContent=`XFRAME / ${Math.round(Number(job.cache_hit_rate)*100)}% HIT`}
function renderJobFeed(j){const allJobs=j.jobs||[];updatePreview(allJobs);updateDiscovery(allJobs);const jobs=allJobs.filter(x=>String(x.kind||"")==="atlas_sphere"||x.viewer_url);$("workerState").textContent=j.worker_running?"WORKER LIVE":"SUITE LIVE";const running=x=>["running","queued","cancelling"].includes(String(x.status).toLowerCase()),newest=rows=>rows.filter(running).sort((a,b)=>Number(b.created||0)-Number(a.created||0))[0],active=newest(jobs)||jobs.find(x=>x.id===state.activeJob);if(active){acceptAssetJob(active.id);checkpoint("dispatched");if(active.nexus_accepted)checkpoint("nexus");checkpoint("worker");showJobProgress(active)}else{const seedJob=newest(allJobs.filter(x=>String(x.kind||"")==="seed_preview"));if(seedJob){acceptAssetJob(seedJob.id);checkpoint("dispatched");if(seedJob.nexus_accepted)checkpoint("nexus");checkpoint("worker");showJobProgress(seedJob)}}$("sessions").innerHTML=jobs.length?jobs.slice(0,6).map(x=>`<button class="session ${x.id===state.activeJob?"active":""}" data-job="${escapeHTML(x.id)}"><span>${escapeHTML(x.prompt||"Motion atlas")}</span><small>${escapeHTML(x.status||"queued")} · ${Number(x.atlas_done??x.step??0).toLocaleString()} / ${Number(x.atlas_total??x.total_steps??0).toLocaleString()}</small></button>`).join(""):'<div class="session empty"><span>NO ACTIVE ATLAS</span><small>Continuity preview is shown above</small></div>';document.querySelectorAll("[data-job]").forEach(b=>b.onclick=()=>{state.activeJob=b.dataset.job;acceptAssetJob(state.activeJob);showJobProgress(jobs.find(x=>x.id===state.activeJob))})}
async function refreshJobs(){try{const r=await fetch("/api/jobs"),j=await r.json();renderJobFeed(j)}catch{}}
function connectStreams(){const jobs=new EventSource("/api/jobs/events");jobs.addEventListener("jobs",e=>{try{renderJobFeed(JSON.parse(e.data))}catch{}});jobs.onerror=()=>{$("workerState").textContent="RECONNECTING"};const gpu=new EventSource("/api/telemetry/events");gpu.addEventListener("gpu",e=>{try{renderGPU(JSON.parse(e.data).gpu)}catch{}});gpu.onerror=()=>{$("computeValue").textContent="RECONNECTING"};const processes=new EventSource("/api/telemetry/processes/events");processes.addEventListener("process",e=>{try{renderGPUProcess(JSON.parse(e.data))}catch{}});const assets=new EventSource("/api/assets/events");assets.addEventListener("asset",e=>{try{const event=JSON.parse(e.data);if(state.acceptedAssetJobs.has(event.job_id))ingestAssetEvent(event);else{const pending=state.pendingAssets.get(event.job_id)||[];pending.push(event);state.pendingAssets.set(event.job_id,pending)}}catch{}});assets.onerror=()=>{$("stageMessage").querySelector("span").textContent="Piper reconnecting to the asset socket."};const model=new EventSource("/api/model/events");model.addEventListener("model",e=>{try{renderModel(JSON.parse(e.data))}catch{}})}
async function modelAction(path){try{const r=await fetch(path,{method:"POST"}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||"Model action failed");$("modelMessage").textContent=String(j.status||"Working").toUpperCase();$("modelProgressBar").classList.add("busy")}catch(e){toast(e.message)}}
function loadThumbnail(img,url,seed){document.querySelectorAll("#filmstrip img").forEach(x=>x.classList.remove("selected"));img.classList.add("selected");$("assetSummary").textContent="Loading selected frame…";const shown=$("assetFrameA");shown.classList.remove("active");shown.onload=()=>{shown.classList.add("active");$("assetSummary").textContent=seed?`Seed ${seed} selected · ready to start`:"Selected frame loaded"};shown.onerror=()=>{$("assetSummary").textContent="Frame failed to load"};shown.src=url;$("assetFrameB").classList.remove("active");if(seed){$("seed").value=seed;state.selectedFlavor={seed:String(seed),url};updateJobReady()}}
function cycleFrame(delta){const frames=[...document.querySelectorAll("#filmstrip img")];if(!frames.length)return;let i=frames.findIndex(x=>x.classList.contains("selected"));i=(i<0?(delta>0?-1:0):i)+delta;i=(i+frames.length)%frames.length;frames[i].click();frames[i].scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"})}
function ingestFrame(d){const url=d.url||d.output_url||d.image_url;if(url&&!state.frames.includes(url)){state.frames.push(url);checkpoint("assets");$("assetSummary").textContent=`${state.frames.length.toLocaleString()} assets received from Piper`;const next=state.assetSide==="A"?$("assetFrameA"):$("assetFrameB"),prior=state.assetSide==="A"?$("assetFrameB"):$("assetFrameA");next.onload=()=>{prior.classList.remove("active");next.classList.add("active")};next.onerror=()=>{$("assetSummary").textContent="Incoming frame failed to load"};next.src=url;state.assetSide=state.assetSide==="A"?"B":"A";$("assetStage").style.display="block";$("sphere").style.display="none";$("stageMessage").style.display="none";const img=document.createElement("img");img.onload=()=>img.classList.remove("loading");img.onerror=()=>img.classList.add("failed");img.classList.add("loading");img.src=url;img.title=d.seed?`Load frame and select seed ${d.seed}`:"Load this frame";img.onclick=()=>loadThumbnail(img,url,d.seed);$("filmstrip").querySelector(".filmEmpty")?.remove();$("filmstrip").appendChild(img);$("filmstrip").scrollLeft=999999}
  if(d.updateProgress){const done=Number(d.completed||state.frames.length),total=Number(d.total||0),pct=total?Math.min(100,done/total*100):0;$("progressBar").style.width=pct+"%";$("progressText").textContent=total?`${done.toLocaleString()} / ${total.toLocaleString()}`:"— / —";if(state.started&&done&&total){const fps=done/((Date.now()-state.started)/1000);$("rate").textContent=fps.toFixed(2)+" fps";$("eta").textContent=Math.max(0,(total-done)/fps/60).toFixed(1)+" min"}}$("currentCell").textContent=d.index==null?"—":String(d.index).padStart(5,"0")}
document.querySelectorAll("[data-run]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-run]").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.runType=b.dataset.run});
const presets={continuity:{mode:"elliptic",seedLock:.58,shellScale:1.02,shellCoupling:.7,cacheThreshold:.22,rates:[.18,.06,-.04,.04,-.02,.01]},cinema:{mode:"elliptic",seedLock:.3,shellScale:1.12,shellCoupling:.92,cacheThreshold:.3,rates:[.32,.11,-.09,.08,-.06,.04]},parallax:{mode:"omega",seedLock:.2,shellScale:1.34,shellCoupling:1.45,cacheThreshold:.24,rates:[.5,.28,-.16,.22,-.12,.09]},dream:{mode:"omega",seedLock:.12,shellScale:1.55,shellCoupling:.55,cacheThreshold:.34,rates:[.72,-.38,.44,.31,-.27,.19]},sway:{mode:"sway",seedLock:.42,shellScale:1.08,shellCoupling:1.1,cacheThreshold:.27,rates:[.24,.09,-.05,.07,-.03,.02]}};
const promptTreatments={continuity:"Unbroken identity-first tracking: preserve exact anatomy, silhouette, material, lighting logic, and spatial orientation from frame to frame; measured physical motion with no morphing, substitution, costume drift, or discontinuous camera jumps.",cinema:"A composed cinematic orbit with deliberate lens language, graceful elliptical camera movement, controlled depth separation, motivated light, restrained spectacle, and stable subject identity throughout the sequence.",parallax:"Pronounced deep parallax: foreground, subject, architecture, and horizon travel at clearly separated rates; wide spatial legibility, strong lateral displacement, coherent perspective, and no flattened backdrop.",dream:"A lucid dream sphere with expressive four-dimensional drift, luminous atmospheric transitions, poetic environmental transformation, and a single unmistakably consistent subject acting as the visual anchor.",sway:"A reversible return-sway movement: travel outward, decelerate, reverse gracefully, and return toward the visual home state with matched composition, identity, rhythm, and spatial continuity."};
document.querySelectorAll("[data-preset]").forEach(b=>b.onclick=()=>{const key=b.dataset.preset,p=presets[key],prompt=$("prompt"),base=prompt.value.split("\\n\\nMotion treatment:")[0].trim();prompt.value=`${base}\\n\\nMotion treatment: ${promptTreatments[key]}`;$("mode").value=p.mode;$("seedLock").value=p.seedLock;$("latentDistance").value=p.shellScale;$("shellCoupling").value=p.shellCoupling;$("cacheThreshold").value=p.cacheThreshold;["dimXY","dimXZ","dimXW","dimYZ","dimYW","dimZW"].forEach((id,i)=>$(id).value=p.rates[i]);document.querySelectorAll(".parameter input,.dimAxis input,#latentDistance").forEach(x=>x.dispatchEvent(new Event("input")));document.querySelectorAll("[data-preset]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");updateJobReady();toast(`${b.querySelector("strong").textContent} prompt generated`)});
function surpriseOrbit(){const keys=Object.keys(presets),key=keys[Math.floor(Math.random()*keys.length)],p=presets[key];$("mode").value=p.mode;$("seedLock").value=Math.max(0,Math.min(.95,p.seedLock+(Math.random()-.5)*.12)).toFixed(2);$("latentDistance").value=Math.max(.01,p.shellScale+(Math.random()-.5)*.18).toFixed(2);$("shellCoupling").value=(p.shellCoupling+(Math.random()-.5)*.3).toFixed(2);$("cacheThreshold").value=p.cacheThreshold;$("seed").value=String(Math.floor(Math.random()*890000000)+10000000);["dimXY","dimXZ","dimXW","dimYZ","dimYW","dimZW"].forEach((id,i)=>$(id).value=(p.rates[i]*(.78+Math.random()*.44)).toFixed(2));document.querySelectorAll(".parameter input,.dimAxis input,#latentDistance").forEach(x=>x.dispatchEvent(new Event("input")));toast(`${key.toUpperCase()} orbit composed · ready to start`);updateJobReady()}
document.querySelectorAll(".groupTitle").forEach(b=>b.onclick=()=>{b.parentElement.classList.toggle("open");b.querySelector("i").textContent=b.parentElement.classList.contains("open")?"−":"+"});
const geometryCopy={elliptic:["ELLIPTIC · CONTROLLED ORBIT","A smooth closed arc around the home identity. Best for stable cinematic motion with gradual change."],omega:["OMEGA / SO(4) · COMPLEX ORBIT","Couples all six rotation planes in four-dimensional latent space. Produces richer viewpoint and form evolution with less predictable motion."],sway:["SWAY · OUT AND RETURN","Moves away from the home state and reverses along a related route. Best for reversible motion and visual return."],oscillatory:["OSCILLATORY · RHYTHMIC PATH","Uses repeating multi-axis waves. Best for cyclical, pulsing, or mechanically rhythmic motion."]},traversalCopy={row_serpentine:"Row serpentine walks each row forward, then reverses the next row to avoid a hard return jump.",column_serpentine:"Column serpentine walks down one column and up the next, favoring vertical neighborhood continuity.",raster:"Raster always moves in one direction and jumps back at each boundary; useful for diagnostics, less smooth for motion."};function updateGeometryHelp(){const g=geometryCopy[$("mode").value];$("geometryName").textContent=g[0];$("geometryHelp").textContent=g[1];$("traversalHelp").textContent=traversalCopy[$("order").value]}$("mode").addEventListener("change",updateGeometryHelp);$("order").addEventListener("change",updateGeometryHelp);
document.querySelectorAll(".parameter input,.dimAxis input,#latentDistance").forEach(input=>input.oninput=()=>{const out=document.querySelector(`output[data-for="${input.id}"]`);if(out)out.value=Number(input.value).toFixed(2);const shell=Math.max(.82,Math.min(1.14,.88+numeric("latentDistance")*.1)),spin=["dimXY","dimXZ","dimXW","dimYZ","dimYW","dimZW"].reduce((n,id)=>n+numeric(id),0)*5;$("sphere").style.setProperty("--shell",shell);$("sphere").style.setProperty("--spin",spin+"deg");$("sphere").style.filter=`drop-shadow(0 0 ${18+numeric("seedLock")*42}px rgba(85,231,238,.24))`});
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-view]").forEach(x=>x.classList.remove("active"));b.classList.add("active");const frame=b.dataset.view==="frame"&&state.frames.length;$("assetStage").style.display=frame?"block":"none";$("sphere").style.display=frame?"none":"block"});
$("focusStage").onclick=()=>{document.querySelector(".workspace").classList.toggle("stageFocused");$("focusStage").textContent=document.querySelector(".workspace").classList.contains("stageFocused")?"↙":"↗";setTimeout(drawMap,350)};
$("indexStart").oninput=updateRange;$("cells").oninput=()=>{$("cellsNumber").value=$("cells").value;updateRange()};$("cellsNumber").oninput=()=>{$("cells").value=Math.max(1,Math.min(65536,numeric("cellsNumber")||1));updateRange()};$("planButton").onclick=renderSeedBatch;$("launchButton").onclick=()=>{if(!state.model.loaded){state.model.pendingPreview=true;$("stageMessage").innerHTML="<strong>LOADING FLUX WORKER</strong><span>The visible prompt will begin in domino batches: 1 → 2 → 4 → 8 → 16.</span>";return modelAction(state.model.downloaded?"/api/model/load":"/api/model/download")}submit(false)};$("launchFromPlan").onclick=()=>{$("manifestDialog").close();submit(false)};$("refreshJobs").onclick=refreshJobs;
document.querySelectorAll(".dialogClose,.dialogCloseButton").forEach(b=>b.onclick=()=>$("manifestDialog").close());
$("helpButton").onclick=()=>toast("Plan a coherent latent path, then launch it into the resident FLUX worker.");
$("downloadModel").onclick=()=>modelAction("/api/model/download");$("loadModel").onclick=()=>modelAction("/api/model/load");
$("atlasForm").addEventListener("input",updateJobReady);document.addEventListener("keydown",e=>{if(["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName))return;if(e.key==="ArrowLeft"){e.preventDefault();cycleFrame(-1)}if(e.key==="ArrowRight"){e.preventDefault();cycleFrame(1)}});seedPage();drawMap();updateRange();updateGeometryHelp();updateJobReady();connectStreams();window.addEventListener("resize",drawMap);
