const $=id=>document.getElementById(id);
const values=()=>({focal:Number($("focal").value),aperture:Number($("aperture").value)/10,focus:Number($("focus").value)/10,squeeze:Number($("squeeze").value)/100,distortion:Number($("distortion").value),halation:Number($("halation").value)});
function toast(s){$("toast").textContent=s;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
function compile(){
  const v=values(),field=v.focal<28?"ULTRA WIDE":v.focal<45?"WIDE":v.focal<70?"NORMAL":v.focal<120?"COMPRESSED":"TELEPHOTO";
  $("focalOut").value=`${v.focal} mm`;$("apertureOut").value=`T${v.aperture.toFixed(1)}`;$("focusOut").value=`${v.focus.toFixed(1)} m`;$("squeezeOut").value=`${v.squeeze.toFixed(2)}×`;$("distortionOut").value=`${v.distortion}%`;$("halationOut").value=`${v.halation}%`;
  $("fieldReadout").textContent=field;$("planeReadout").textContent=`${v.focus.toFixed(1)} M`;$("gateReadout").textContent=`${v.squeeze.toFixed(2)}×`;
  $("lensAssembly").style.setProperty("--focal",(v.focal-14)/186);$("lensAssembly").style.setProperty("--aperture",(v.aperture-1.2)/14.8);
  $("compiledOptics").textContent=`${$("opticPrompt").value.trim()}. Photographed through a ${v.focal}mm ${$("character").value} cinema lens at T${v.aperture.toFixed(1)}, focus plane at ${v.focus.toFixed(1)} meters, ${$("focusBehavior").value}, ${v.squeeze.toFixed(2)}x anamorphic squeeze, ${v.distortion}% signed optical distortion, ${v.halation}% controlled halation, physically coherent depth of field, consistent lens geometry and optical behavior across the sequence.`;
}
const presets={anamorphic:[50,20,55,200,"vintage low-contrast",8,35],portrait:[85,18,30,100,"Cooke warmth",0,18],documentary:[35,40,70,100,"modern neutral",-3,6],macro:[100,28,5,100,"Zeiss micro-contrast",2,10]};
document.querySelectorAll("[data-optic]").forEach(b=>b.onclick=()=>{const p=presets[b.dataset.optic];["focal","aperture","focus","squeeze"].forEach((id,i)=>$(id).value=p[i]);$("character").value=p[4];$("distortion").value=p[5];$("halation").value=p[6];document.querySelectorAll("[data-optic]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");compile()});
document.querySelectorAll("input,textarea,select").forEach(x=>x.addEventListener("input",compile));
$("copyOptics").onclick=async()=>{await navigator.clipboard.writeText($("compiledOptics").textContent);toast("Optical instruction copied")};
$("generateOptics").onclick=async()=>{const button=$("generateOptics");button.disabled=true;$("opticState").textContent="DISPATCHING OPTICAL PROOFS";try{const base=String(Date.now()%800000000+10000000),r=await fetch("/api/render",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:$("compiledOptics").textContent,model:"dev",backend:"cuda",width:512,height:512,steps:16,guidance:4.2,seed:base,filename:`optical-proof-${Date.now()}.png`,iterations:8})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||"Dispatch failed");$("opticState").textContent="PIPER · PROOFS IN FLIGHT";toast("Eight optical proofs dispatched")}catch(e){$("opticState").textContent="OPTICAL BENCH ATTENTION";toast(e.message)}finally{button.disabled=false}};
const assets=new EventSource("/api/assets/events");assets.addEventListener("asset",e=>{const a=JSON.parse(e.data).asset||{};if(!String(a.name||"").startsWith("optical-proof-"))return;const img=document.createElement("img");img.src=a.access_url;img.title=`Seed ${a.seed||"—"}`;$("opticAssets").prepend(img);$("opticState").textContent="PIPER · OPTICAL PROOF RECEIVED"});
compile();
