const $=id=>document.getElementById(id),KEY="flux.motion.queue.v1";
let items=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const studies=[
["atlas-equine-lateral-motion","A dark horse in powerful lateral motion through rain-lit Samara, exact anatomy, stable identity, readable hoof contacts, cinematic architectural parallax"],
["atlas-orbital-camera-continuity","A solitary silver figure on a basalt platform as the camera completes a controlled orbital move, consistent silhouette, background geometry, scale, and screen direction"],
["atlas-volumetric-light-transport","A monumental glass pavilion at blue hour, shafts of amber light moving through fog, physically coherent reflections, refraction, occlusion, and exposure"],
["atlas-material-response","An editorial arrangement of brushed titanium, wet obsidian, translucent resin, silk, and weathered leather under a traveling studio light"],
["atlas-character-identity","A weathered astronaut crossing a red salt basin, facial identity, suit markings, proportions, and carried equipment remaining exact through pose changes"],
["atlas-temporal-motion","A dancer executing a full turning leap in a stark concrete hall, anatomically plausible anticipation, airborne phase, landing, fabric inertia, and hair motion"],
["atlas-topology-stress","An intricate kinetic sculpture unfolding from a compact polyhedron into interlocking ribbons without intersections, duplication, broken joints, or impossible topology"],
["atlas-depth-parallax","A camera pushing through layered jungle ruins toward a luminous monolith, strong foreground occlusion, measured midground drift, and stable distant perspective"],
["atlas-atmospheric-weather","A fishing vessel crossing a violent midnight squall, evolving wave structure, rain direction, spray, lightning illumination, and hull continuity"],
["atlas-production-gauntlet","A continuous cinematic shot moving from macro mechanical detail to a wide autonomous atelier floor, coherent scale transition, legible action, stable assets, and no dropped frames"]
];
function defaultItem([id,prompt],i){return{key:`seed-${i+1}-${id}`,status:"draft",created_at:Date.now()+i,payload:{id,prompt,cells:i===9?256:64,size:i===9?768:512,steps:i===9?48:36,guidance:4.4,seed:String(2026072801+i),mode:["elliptic","omega","sway","oscillatory"][i%4],backend:"cuda",run_type:"spot",sample_mode:"nested_sparse",traversal_order:"row_serpentine",adapter:"atlas-xframe-cache"}}}
function load(){try{const stored=localStorage.getItem(KEY);items=stored===null?studies.map(defaultItem):JSON.parse(stored)}catch{items=studies.map(defaultItem)}save()}
function save(){localStorage.setItem(KEY,JSON.stringify(items));render()}
function toast(message){$("toast").textContent=message;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2600)}
function spec(){return{id:$("queueName").value.trim(),prompt:$("queuePrompt").value.trim(),cells:+$("queueCells").value,size:+$("queueSize").value,steps:+$("queueSteps").value,guidance:+$("queueGuidance").value,seed:$("queueSeed").value.trim()||"random",mode:$("queueMode").value,backend:"cuda",run_type:"spot",sample_mode:"nested_sparse",traversal_order:"row_serpentine",adapter:"atlas-xframe-cache"}}
function render(){const pending=items.filter(x=>x.status==="draft").length,accepted=items.filter(x=>x.status==="accepted").length,failed=items.filter(x=>x.status==="failed").length;$("pendingCount").textContent=pending;$("acceptedCount").textContent=accepted;$("failedCount").textContent=failed;$("queueState").classList.toggle("offline",failed>0);$("queueState").lastElementChild.textContent=failed?`${failed} NEXUS FAILURE${failed===1?"":"S"}`:"LOCAL QUEUE READY";$("queueList").innerHTML=items.map((x,i)=>`<article class="queueCard ${esc(x.status)}"><div class="queueOrdinal">${String(i+1).padStart(2,"0")}</div><div class="queueCopy"><div><strong>${esc(x.payload.id)}</strong><span>${esc(x.status==="accepted"?"NEXUS ACCEPTED":x.status==="failed"?"NEXUS REJECTED":"LOCAL DRAFT")}</span></div><p>${esc(x.payload.prompt)}</p><small>${x.payload.cells} cells · ${x.payload.size}px · ${x.payload.steps} steps · ${esc(x.payload.mode)}${x.receipt?` · ${esc(x.receipt)}`:""}</small>${x.error?`<b>${esc(x.error)}</b>`:""}</div><div class="queueActions"><button data-action="up" data-id="${esc(x.key)}">↑</button><button data-action="down" data-id="${esc(x.key)}">↓</button><button data-action="launch" data-id="${esc(x.key)}">LAUNCH</button><button data-action="remove" data-id="${esc(x.key)}">×</button></div></article>`).join("")||'<div class="queueEmpty">No studies staged. Build the first one at left.</div>'}
async function launch(item){item.status="dispatching";save();try{const r=await fetch("/api/atlas/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(item.payload)}),j=await r.json();const nexus=j.nexus||{},accepted=r.ok&&j.ok===true&&nexus.ok===true&&nexus.verified===true;if(!accepted)throw new Error(nexus.error||`Nexus did not provide a verified receipt (${nexus.status||"no status"})`);item.status="accepted";item.receipt=nexus.receipt_id||nexus.job_id||j.job?.id||item.payload.id;item.error=""}catch(e){item.status="failed";item.error=e.message||String(e)}save()}
$("queueForm").addEventListener("submit",e=>{e.preventDefault();const payload=spec();items.push({key:crypto.randomUUID(),status:"draft",payload,created_at:Date.now()});save();$("queueName").value="";$("queuePrompt").value="";toast("Study added to Queue")});
$("queueList").addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;const i=items.findIndex(x=>x.key===b.dataset.id);if(i<0)return;if(b.dataset.action==="remove")items.splice(i,1);if(b.dataset.action==="up"&&i>0)[items[i-1],items[i]]=[items[i],items[i-1]];if(b.dataset.action==="down"&&i<items.length-1)[items[i+1],items[i]]=[items[i],items[i+1]];if(b.dataset.action==="launch")await launch(items[i]);else save()});
$("launchAll").addEventListener("click",async()=>{for(const item of items.filter(x=>x.status==="draft"||x.status==="failed"))await launch(item);toast(items.some(x=>x.status==="failed")?"Nexus rejected one or more jobs":"Pending studies accepted")});
load();
