const $=id=>document.getElementById(id),KEY="flux.motion.queue.v1";
let items=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function load(){try{items=JSON.parse(localStorage.getItem(KEY)||"[]")}catch{items=[]}render()}
function save(){localStorage.setItem(KEY,JSON.stringify(items));render()}
function toast(message){$("toast").textContent=message;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2600)}
function spec(){return{id:$("queueName").value.trim(),prompt:$("queuePrompt").value.trim(),cells:+$("queueCells").value,size:+$("queueSize").value,steps:+$("queueSteps").value,guidance:+$("queueGuidance").value,seed:$("queueSeed").value.trim()||"random",mode:$("queueMode").value,backend:"cuda",run_type:"spot",sample_mode:"nested_sparse",traversal_order:"row_serpentine",adapter:"atlas-xframe-cache"}}
function render(){const pending=items.filter(x=>x.status==="draft").length,accepted=items.filter(x=>x.status==="accepted").length,failed=items.filter(x=>x.status==="failed").length;$("pendingCount").textContent=pending;$("acceptedCount").textContent=accepted;$("failedCount").textContent=failed;$("queueState").classList.toggle("offline",failed>0);$("queueState").lastElementChild.textContent=failed?`${failed} NEXUS FAILURE${failed===1?"":"S"}`:"LOCAL QUEUE READY";$("queueList").innerHTML=items.map((x,i)=>`<article class="queueCard ${esc(x.status)}"><div class="queueOrdinal">${String(i+1).padStart(2,"0")}</div><div class="queueCopy"><div><strong>${esc(x.payload.id)}</strong><span>${esc(x.status==="accepted"?"NEXUS ACCEPTED":x.status==="failed"?"NEXUS REJECTED":"LOCAL DRAFT")}</span></div><p>${esc(x.payload.prompt)}</p><small>${x.payload.cells} cells · ${x.payload.size}px · ${x.payload.steps} steps · ${esc(x.payload.mode)}${x.receipt?` · ${esc(x.receipt)}`:""}</small>${x.error?`<b>${esc(x.error)}</b>`:""}</div><div class="queueActions"><button data-action="up" data-id="${esc(x.key)}">↑</button><button data-action="down" data-id="${esc(x.key)}">↓</button><button data-action="launch" data-id="${esc(x.key)}">LAUNCH</button><button data-action="remove" data-id="${esc(x.key)}">×</button></div></article>`).join("")||'<div class="queueEmpty">No studies staged. Build the first one at left.</div>'}
async function launch(item){item.status="dispatching";save();try{const r=await fetch("/api/atlas/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(item.payload)}),j=await r.json();const nexus=j.nexus||{},accepted=r.ok&&j.ok===true&&nexus.ok===true&&nexus.verified===true;if(!accepted)throw new Error(nexus.error||`Nexus did not provide a verified receipt (${nexus.status||"no status"})`);item.status="accepted";item.receipt=nexus.receipt_id||nexus.job_id||j.job?.id||item.payload.id;item.error=""}catch(e){item.status="failed";item.error=e.message||String(e)}save()}
$("queueForm").addEventListener("submit",e=>{e.preventDefault();const payload=spec();items.push({key:crypto.randomUUID(),status:"draft",payload,created_at:Date.now()});save();$("queueName").value="";$("queuePrompt").value="";toast("Study added to Queue")});
$("queueList").addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;const i=items.findIndex(x=>x.key===b.dataset.id);if(i<0)return;if(b.dataset.action==="remove")items.splice(i,1);if(b.dataset.action==="up"&&i>0)[items[i-1],items[i]]=[items[i],items[i-1]];if(b.dataset.action==="down"&&i<items.length-1)[items[i+1],items[i]]=[items[i],items[i+1]];if(b.dataset.action==="launch")await launch(items[i]);else save()});
$("launchAll").addEventListener("click",async()=>{for(const item of items.filter(x=>x.status==="draft"||x.status==="failed"))await launch(item);toast(items.some(x=>x.status==="failed")?"Nexus rejected one or more jobs":"Pending studies accepted")});
load();
