const $=id=>document.getElementById(id),KEY="flux.motion.queue.v1";
let items=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const studies=[
["atlas-equine-lateral-motion","A dark horse in powerful lateral motion through rain-lit Samara, exact anatomy, stable identity, readable hoof contacts, cinematic architectural parallax"],
["atlas-orbital-camera-continuity","A solitary silver figure on a basalt platform as the camera completes a controlled orbital move, consistent silhouette, background geometry, scale, and screen direction"],
["atlas-volumetric-light-transport","A monumental glass pavilion at blue hour, shafts of amber light moving through fog, physically coherent reflections, refraction, occlusion, and exposure"],
["atlas-material-response","An editorial arrangement of brushed titanium, wet obsidian, translucent resin, silk, and weathered leather under a traveling studio light"],
["atlas-character-identity","A weathered astronaut crossing a red salt basin, facial identity, suit markings, proportions, and carried equipment remaining exact through pose changes"],
["atlas-temporal-motion","A dancer executing a full turning leap in a stark concrete hall, anatomically plausible anticipation, airborne phase, landing, fabric inertia, and hair motion"],
["atlas-topology-stress","An intricate kinetic sculpture unfolding from a compact polyhedron into interlocking ribbons without intersections, duplication, broken joints, or impossible topology"],
["atlas-depth-parallax","A camera pushing through layered jungle ruins toward a luminous monolith, strong foreground occlusion, measured midground drift, and stable distant perspective"],
["atlas-atmospheric-weather","A fishing vessel crossing a violent midnight squall, evolving wave structure, rain direction, spray, lightning illumination, and hull continuity"],
["atlas-production-gauntlet","A continuous cinematic shot moving from macro mechanical detail to a wide autonomous atelier floor, coherent scale transition, legible action, stable assets, and no dropped frames"]
];
const beautyDrift=[
"A pale horse stands in shallow silver water at first light, quiet horizon, exact anatomy, restrained pearl and charcoal palette, lucid naturalism",
"The pale horse begins walking through silver water, low ripples widening around each hoof, quiet horizon, pearl light acquiring a trace of rose",
"The walking horse crosses a flooded marble court, distant columns appearing through morning mist, reflections remaining geometrically exact",
"The marble court opens into a submerged garden, white irises and dark reeds entering the foreground, the horse moving with ceremonial calm",
"The garden grows warmer and less architectural, rose mist threading through reeds while petals follow the horse's wake in coherent currents",
"Petals lengthen into translucent ribbons of color, still governed by water and wind, the horse remaining tangible and anatomically constant",
"The silver water becomes a mirror of a lavender sky, ribbons rising into slow helices around the horse without touching or obscuring it",
"The horizon dissolves into immense planes of opal light, horse and reflection crossing the seam between water and sky, serene spatial continuity",
"Opal planes bend into a luminous valley of soft crystalline forms, recognizable terrain emerging from light while the horse remains the visual anchor",
"The crystalline valley blooms with impossible glass flora, cyan shadows and apricot highlights, delicate refraction, measured forward movement",
"Glass flora releases constellations of tiny lights that organize into flowing currents, beauty shifting from botanical to celestial without a cut",
"The horse walks through a weightless nocturne of indigo currents and gold particles, ground implied only by a faint reflective plane",
"Gold particles gather into distant floating architecture, arches made from light and negative space, majestic scale with intimate calm",
"The luminous architecture thins into calligraphic trajectories, horse, path, and city becoming an elegant system of moving lines and radiant intervals",
"At the far edge of representation, the horse becomes a barely figurative constellation crossing a vast field of color-wind, still carrying the original gait, proportions, and quiet grace"
].map((prompt,i)=>[`beauty-drift-${String(i+1).padStart(2,"0")}`,prompt]);
function defaultItem([id,prompt],i){return{key:`seed-${i+1}-${id}`,status:"draft",created_at:Date.now()+i,payload:{id,prompt,cells:i===9?256:64,size:i===9?768:512,steps:i===9?48:36,guidance:4.4,seed:String(2026072801+i),mode:["elliptic","omega","sway","oscillatory"][i%4],backend:"cuda",run_type:"spot",sample_mode:"nested_sparse",traversal_order:"row_serpentine",adapter:"atlas-xframe-cache"}}}
function driftItem([id,prompt],i){return{key:`drift-${i+1}-${id}`,status:"draft",created_at:Date.now()+100+i,payload:{id,prompt,cells:2048,size:768,steps:32,guidance:4.4,seed:"314159265",seed_b:271828182,seed_c:161803398,seed_d:141421356,dimension_rates:[.18,.06,-.04,.04,-.02,.01],shell_scale:.42,seed_lock:.68,shell_coupling:.82,mode:"elliptic",backend:"cuda",run_type:"spot",sample_mode:"even",index_start:0,index_end:65536,traversal_order:"row_serpentine",adapter:"atlas-xframe-cache",cache_threshold:.18,cache_downsample:1,cache_warmup:0}}}
function load(){try{const stored=localStorage.getItem(KEY);items=stored===null?studies.map(defaultItem):JSON.parse(stored)}catch{items=studies.map(defaultItem)}const driftSpecs=beautyDrift.map(driftItem),byID=new Map(driftSpecs.map(x=>[x.payload.id,x]));for(const item of items){const revised=byID.get(item.payload?.id);if(revised&&item.status!=="accepted")item.payload={...item.payload,...revised.payload};if(item.status!=="accepted")Object.assign(item.payload,{cells:2048,steps:32,shell_scale:.42,seed_lock:.68,shell_coupling:.82,run_type:"spot",sample_mode:"even",index_start:0,index_end:65536})}const ids=new Set(items.map(x=>x.payload?.id));driftSpecs.filter(x=>!ids.has(x.payload.id)).forEach(x=>items.push(x));save()}
function save(){localStorage.setItem(KEY,JSON.stringify(items));render()}
function toast(message){$("toast").textContent=message;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2600)}
function spec(){return{id:$("queueName").value.trim(),prompt:$("queuePrompt").value.trim(),cells:+$("queueCells").value,size:+$("queueSize").value,steps:+$("queueSteps").value,guidance:+$("queueGuidance").value,seed:$("queueSeed").value.trim()||"random",mode:$("queueMode").value,backend:"cuda",run_type:"spot",sample_mode:"nested_sparse",traversal_order:"row_serpentine",adapter:"atlas-xframe-cache"}}
function render(){const pending=items.filter(x=>x.status==="draft").length,accepted=items.filter(x=>x.status==="accepted").length,failed=items.filter(x=>x.status==="failed").length;$("pendingCount").textContent=pending;$("acceptedCount").textContent=accepted;$("failedCount").textContent=failed;$("queueState").classList.toggle("offline",failed>0);$("queueState").lastElementChild.textContent=failed?`${failed} NEXUS FAILURE${failed===1?"":"S"}`:"LOCAL QUEUE READY";$("queueList").innerHTML=items.map((x,i)=>`<article class="queueCard ${esc(x.status)}"><div class="queueOrdinal">${String(i+1).padStart(2,"0")}</div><div class="queueCopy"><div><strong>${esc(x.payload.id)}</strong><span>${esc(x.status==="accepted"?"NEXUS ACCEPTED":x.status==="failed"?"NEXUS REJECTED":"LOCAL DRAFT")}</span></div><p>${esc(x.payload.prompt)}</p><small>${x.payload.cells} cells · ${x.payload.size}px · ${x.payload.steps} steps · ${esc(x.payload.mode)}${x.receipt?` · ${esc(x.receipt)}`:""}</small>${x.error?`<b>${esc(x.error)}</b>`:""}</div><div class="queueActions"><button data-action="up" data-id="${esc(x.key)}">↑</button><button data-action="down" data-id="${esc(x.key)}">↓</button><button data-action="launch" data-id="${esc(x.key)}">LAUNCH</button><button data-action="remove" data-id="${esc(x.key)}">×</button></div></article>`).join("")||'<div class="queueEmpty">No studies staged. Build the first one at left.</div>'}
async function launch(item){item.status="dispatching";save();try{const r=await fetch("/api/atlas/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(item.payload)}),j=await r.json();const nexus=j.nexus||{},accepted=r.ok&&j.ok===true&&nexus.ok===true&&nexus.verified===true;if(!accepted)throw new Error(nexus.error||`Nexus did not provide a verified receipt (${nexus.status||"no status"})`);item.status="accepted";item.receipt=nexus.receipt_id||nexus.job_id||j.job?.id||item.payload.id;item.error=""}catch(e){item.status="failed";item.error=e.message||String(e)}save()}
$("queueForm").addEventListener("submit",e=>{e.preventDefault();const payload=spec();items.push({key:crypto.randomUUID(),status:"draft",payload,created_at:Date.now()});save();$("queueName").value="";$("queuePrompt").value="";toast("Study added to Queue")});
$("queueList").addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;const i=items.findIndex(x=>x.key===b.dataset.id);if(i<0)return;if(b.dataset.action==="remove")items.splice(i,1);if(b.dataset.action==="up"&&i>0)[items[i-1],items[i]]=[items[i],items[i-1]];if(b.dataset.action==="down"&&i<items.length-1)[items[i+1],items[i]]=[items[i],items[i+1]];if(b.dataset.action==="launch")await launch(items[i]);else save()});
$("launchAll").addEventListener("click",async()=>{for(const item of items.filter(x=>x.status==="draft"||x.status==="failed"))await launch(item);toast(items.some(x=>x.status==="failed")?"Nexus rejected one or more jobs":"Pending studies accepted")});
load();
