const $=id=>document.getElementById(id);
const state={data:{jobs:[],assets:[],seeds:[]},selected:null,filter:"all"};
const esc=s=>{const d=document.createElement("div");d.textContent=s??"";return d.innerHTML};
const stamp=n=>n?new Date(n*1000).toLocaleString():"—";
function matches(j){const q=$("registrySearch").value.trim().toLowerCase(),status=String(j.status).toLowerCase();if(state.filter==="running"&&!["running","queued","cancelling"].includes(status))return false;if(state.filter==="done"&&status!=="done")return false;if(state.filter==="error"&&!["error","cancelled"].includes(status))return false;return !q||[j.id,j.prompt,j.seed,j.status,j.phase].some(v=>String(v||"").toLowerCase().includes(q))}
function render(){
 const d=state.data;$("jobCount").textContent=d.jobs.length.toLocaleString();$("assetCount").textContent=d.assets.length.toLocaleString();$("seedCount").textContent=d.seeds.length.toLocaleString();$("ledgerStamp").textContent=`LIVE · ${new Date().toLocaleTimeString()}`;
 const jobs=d.jobs.filter(matches);$("jobLedger").innerHTML=jobs.length?jobs.map(j=>{const n=Number(j.progress||0),t=Number(j.total||0),pct=t?Math.min(100,n/t*100):String(j.status).toLowerCase()==="done"?100:0;return `<button class="ledgerRow ${state.selected===j.id?"selected":""}" data-job="${esc(j.id)}"><i class="${esc(j.status)}"></i><span><strong>${esc(j.id)}</strong><small>${esc(j.kind||"render")} · ${stamp(j.updated_at)}</small></span><b>${esc(String(j.status||"unknown").toUpperCase())}</b><span class="ledgerProgress"><em style="width:${pct}%"></em></span></button>`}).join(""):'<div class="detailEmpty">NO MATCHING RECEIPTS</div>';
 document.querySelectorAll("[data-job]").forEach(b=>b.onclick=()=>{state.selected=b.dataset.job;render();renderDetail()});renderDetail()
}
function assetCards(assets){return assets.length?assets.map(a=>`<a href="${esc(a.access_url)}" target="_blank"><img src="${esc(a.access_url)}" loading="lazy"><span>${esc(a.path||a.access_url)}</span><small>${esc(a.job_id||"UNASSIGNED")} · ${esc(a.id)} · CELL ${a.cell_index}</small></a>`).join(""):'<div class="detailEmpty">No asset receipt yet.</div>'}
function renderDetail(){if(state.selected==="__assets__"){$("registryDetail").innerHTML=`<div class="detailHead"><span>ASSET VAULT</span><b>DIRECT LOCATIONS</b></div><h2>All received assets</h2><div class="detailPrompt"><span>AUDIT GUARANTEE</span><p>Every item below retains its stable receipt ID, originating job, filesystem-relative path, and directly openable URL.</p></div><div class="assetTitle"><span>LOCATABLE ASSETS</span><strong>${state.data.assets.length}</strong></div><div class="auditAssets">${assetCards(state.data.assets)}</div>`;return}const j=state.data.jobs.find(x=>x.id===state.selected);if(!j){$("registryDetail").innerHTML='<div class="detailEmpty"><span>SELECT A RECEIPT</span><p>Choose a job to inspect its state, prompt, seed lineage, and every associated asset.</p></div>';return}const assets=state.data.assets.filter(a=>a.job_id===j.id),seed=state.data.seeds.find(s=>s.seed===j.seed);$("registryDetail").innerHTML=`<div class="detailHead"><span>JOB RECEIPT</span><b>${esc(j.status)}</b></div><h2>${esc(j.id)}</h2><div class="detailFacts"><div><span>PHASE</span><strong>${esc(j.phase||"—")}</strong></div><div><span>BACKEND</span><strong>${esc(j.backend||"—")}</strong></div><div><span>SEED</span><strong>${esc(j.seed||"—")}</strong></div><div><span>UPDATED</span><strong>${stamp(j.updated_at)}</strong></div></div><div class="detailPrompt"><span>DESCRIPTION</span><p>${esc(seed?.description||j.prompt||"No description recorded")}</p></div><div class="assetTitle"><span>LOCATABLE ASSETS</span><strong>${assets.length}</strong></div><div class="auditAssets">${assetCards(assets)}</div>`}
async function load(){try{const r=await fetch("/api/atlas/catalog"),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||"Catalog unavailable");state.data=j;$("registryState").textContent="LIVE CATALOG";render()}catch(e){$("registryState").textContent="CATALOG ATTENTION"}}
$("registrySearch").oninput=render;$("assetVault").onclick=()=>{state.selected="__assets__";renderDetail()};document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});
const jobs=new EventSource("/api/jobs/events");jobs.addEventListener("jobs",load);const assets=new EventSource("/api/assets/events");assets.addEventListener("asset",load);load();
const model=new EventSource("/api/model/events");model.addEventListener("model",e=>{const m=JSON.parse(e.data),top=$("modelTopState");top.className="modelTopState "+(m.loaded?"loaded":m.downloaded?"downloaded":"");top.lastChild.textContent=m.loaded?" MODEL LOADED":m.downloaded?" MODEL READY":" MODEL MISSING"});
