const $=id=>document.getElementById(id);
const esc=s=>{const d=document.createElement("div");d.textContent=s??"";return d.innerHTML};
let assets=[],jobs=[],mode="images",setFilter="",viewed=[],viewIndex=0,motionTimer=null,swipeX=null,swipeCarry=0,displayLimit=180;
const diagnostic=v=>/(\bproof\b|motion-probe)/i.test(String(v||""));
const matching=()=>{const q=$("registrySearch").value.trim().toLowerCase();return assets.filter(a=>(!setFilter||a.job_id===setFilter)&&(!q||String(a.path||a.access_url).toLowerCase().includes(q)))};
const thumb=a=>`/api/asset/thumbnail?w=384&src=${encodeURIComponent(a.access_url)}`;
function imageCard(a,i){const eager=i<12;return `<button class="assetCard" style="--reveal:${Math.min(i,18)*34}ms" data-asset="${i}"><span class="assetGlow"></span><img src="${esc(thumb(a))}" loading="${eager?"eager":"lazy"}" decoding="async" ${i<6?'fetchpriority="high"':""} alt=""><span>${esc((a.path||a.access_url).split("/").pop())}</span><small>${esc(a.path||a.access_url)}</small></button>`}
function revealImages(){document.querySelectorAll("#assetWall img").forEach(img=>{const ready=()=>img.closest("button")?.classList.add("imageReady");if(img.complete&&img.naturalWidth)ready();else img.addEventListener("load",ready,{once:true})})}
function render(){
 const visible=matching();
 if(mode==="sets"){const groups=new Map();for(const a of visible){if(!groups.has(a.job_id))groups.set(a.job_id,[]);groups.get(a.job_id).push(a)}$("assetWall").classList.add("setWall");$("assetWall").innerHTML=groups.size?[...groups].map(([id,items],i)=>`<button class="setCard assetCard" style="--reveal:${Math.min(i,12)*45}ms" data-set="${esc(id)}"><span class="setMosaic">${items.slice(0,4).map((a,n)=>`<img src="${esc(thumb(a))}" loading="${i<3?"eager":"lazy"}" decoding="async" ${i===0&&n<2?'fetchpriority="high"':""}>`).join("")}</span><strong>${items.length.toLocaleString()} IMAGES</strong><small>OPEN SETTINGS + COLLECTION</small></button>`).join(""):'<div class="detailEmpty">No generated sets yet.</div>';document.querySelectorAll("[data-set]").forEach(b=>b.onclick=()=>showCollection(b.dataset.set))}else{const shown=visible.slice(0,displayLimit);$("assetWall").classList.remove("setWall");$("assetWall").innerHTML=visible.length?shown.map(imageCard).join("")+(visible.length>shown.length?`<button class="galleryMore" id="galleryMore">REVEAL ${Math.min(180,visible.length-shown.length)} MORE<br><small>${(visible.length-shown.length).toLocaleString()} REMAIN</small></button>`:""):'<div class="detailEmpty">No generated assets yet.</div>';document.querySelectorAll("[data-asset]").forEach(b=>b.onclick=()=>showAsset(Number(b.dataset.asset),visible));if($("galleryMore"))$("galleryMore").onclick=()=>{displayLimit+=180;render()}}
 revealImages();
 $("assetCount").textContent=assets.length.toLocaleString();$("ledgerStamp").textContent=setFilter?`SET · ${visible.length} IMAGES`:`LIVE · ${new Date().toLocaleTimeString()}`
}
function syncModes(){document.querySelectorAll("[data-gallery-mode]").forEach(b=>b.classList.toggle("active",b.dataset.galleryMode===mode))}
function preloadAround(){for(let d=-10;d<=10;d++){const a=viewed[(viewIndex+d+viewed.length)%viewed.length];if(a){const img=new Image();img.src=a.access_url}}}
function showAsset(i,list=matching()){viewed=list;viewIndex=(i+viewed.length)%viewed.length;const a=viewed[viewIndex];if(!a)return;$("assetViewerImage").classList.add("loading");$("assetViewerImage").onload=()=>$("assetViewerImage").classList.remove("loading");$("assetViewerImage").src=a.access_url;$("assetViewerLabel").textContent=`${viewIndex+1} / ${viewed.length} · ${(a.path||a.access_url).split("/").pop()}`;preloadAround();if(!$("assetViewer").open)$("assetViewer").showModal()}
function cycle(d){if(viewed.length)showAsset((viewIndex+d+viewed.length)%viewed.length,viewed)}
function toggleMotion(){if(motionTimer){clearInterval(motionTimer);motionTimer=null;$("motionPlay").textContent="▶ PLAY MOTION";return}$("motionPlay").textContent="Ⅱ PAUSE";motionTimer=setInterval(()=>cycle(1),85)}
function showCollection(id){const job=jobs.find(x=>x.id===id)||{},items=assets.filter(x=>x.job_id===id);$("collectionTitle").textContent=job.prompt||"Generated collection";$("collectionSettings").innerHTML=[["Resolution",job.width&&job.height?`${job.width} × ${job.height}`:"—"],["Steps",job.steps||job.total_steps||"—"],["Guidance",job.guidance||"—"],["Latent distance",job.latent_distance||"—"],["Seed",job.seed||"—"],["Images",items.length]].map(([k,v])=>`<div><span>${k}</span><strong>${esc(v)}</strong></div>`).join("");$("openCollection").onclick=()=>{$("collectionViewer").close();setFilter=id;mode="images";syncModes();render()};$("collectionViewer").showModal()}
async function load(){requestAnimationFrame(()=>document.body.classList.add("galleryReady"));try{const r=await fetch("/api/atlas/catalog"),j=await r.json();if(!r.ok||!j.ok)throw Error();assets=(j.assets||[]).filter(a=>!diagnostic(a.job_id)&&!diagnostic(a.path));jobs=(j.jobs||[]).filter(x=>!diagnostic(x.id)&&!diagnostic(x.prompt));$("jobCount").textContent=jobs.length.toLocaleString();$("seedCount").textContent=(j.seeds||[]).filter(x=>!diagnostic(x.source_job_id)).length.toLocaleString();$("registryState").textContent="LIVE ASSETS";render()}catch{$("registryState").textContent="ASSET FEED ATTENTION"}}
$("registrySearch").oninput=render;$("assetVault").onclick=()=>{setFilter="";mode="images";syncModes();render()};document.querySelectorAll("[data-gallery-mode]").forEach(b=>b.onclick=()=>{mode=b.dataset.galleryMode;setFilter="";syncModes();render()});$("closeAssetViewer").onclick=()=>{if(motionTimer)toggleMotion();$("assetViewer").close()};$("assetPrev").onclick=()=>cycle(-1);$("assetNext").onclick=()=>cycle(1);$("motionPlay").onclick=toggleMotion;document.addEventListener("keydown",e=>{if(!$("assetViewer").open)return;if(e.key==="ArrowLeft"){e.preventDefault();cycle(-1)}if(e.key==="ArrowRight"){e.preventDefault();cycle(1)}if(e.key===" "){e.preventDefault();toggleMotion()}});
$("assetViewerImage").addEventListener("pointerdown",e=>{swipeX=e.clientX;swipeCarry=0;e.currentTarget.setPointerCapture(e.pointerId)});
$("assetViewerImage").addEventListener("pointermove",e=>{if(swipeX==null)return;swipeCarry+=e.clientX-swipeX;swipeX=e.clientX;while(Math.abs(swipeCarry)>=22){cycle(swipeCarry<0?1:-1);swipeCarry+=swipeCarry<0?22:-22}});
$("assetViewerImage").addEventListener("pointerup",()=>{swipeX=null;swipeCarry=0});$("assetViewerImage").addEventListener("pointercancel",()=>{swipeX=null;swipeCarry=0});
$("closeCollectionViewer").onclick=()=>$("collectionViewer").close();
const stream=new EventSource("/api/assets/events");stream.addEventListener("asset",e=>{const event=JSON.parse(e.data),a=event.asset||{};if(diagnostic(event.job_id)||diagnostic(a.path))return;if(!assets.some(x=>x.id===a.id)){assets.unshift({...a,job_id:event.job_id});render()}});
const model=new EventSource("/api/model/events");model.addEventListener("model",e=>{const m=JSON.parse(e.data),top=$("modelTopState");top.className="modelTopState "+(m.loaded?"loaded":m.downloaded?"downloaded":"");top.lastChild.textContent=m.loaded?" MODEL LOADED":m.downloaded?" MODEL READY":" MODEL MISSING"});
load();
